### ISSUE TITLE
MK802 Mini PC For Android: Wi-Fi not working

### ISSUE THREAD

**Issue by SonOfSardaar** [johang/sd-card-images#110]
Device: MK802
WIFI: Realtek RTL8188CUS (Driver: rtl8192cu)
Issue: wpa suppliant kills the wifi driver/interface

Flashed bookworm image which had no wifi connnectivity, had to plug in ethernet cable with usb hub to connect to network. wireless interface is listed by not connected for which instructions are missing on how to connect to  wifi network. I tried supplying wpa_suppliant.conf file but does not connect to wifi. And also kills the listed interface . i.e. i cannot see wifi interface with "ip a" or "iwconfig" etc. Note. it does list the wireless interface before i start meddling with it. Only reflash brings the interface back in the list.

**Comment by johang** [comment]
You probably have to install firmware for the WLAN chip.

https://wiki.debian.org/rtl819x
