### ISSUE TITLE
how to setup build config for orange pi pc?

### ISSUE THREAD

**Issue by lucasmz1** [johang/sd-card-images#111]
here's my questioning: how do I setup u-boot for my board since I want a local build? I've tired this command here sudo docker run --rm -v /tmp/sd-images:/artifacts sd-images build-boot orangepipc allwinner-h3 arm but no effect.
can you give me the details of how to build using your build system?
thank you!

**Comment by johang** [comment]
Syntax is `build-boot BOARD_ID CHIP_ID U_BOOT_DEFCONFIG BUILD_TUPLE`.

You can find the parameters in [boards.csv](https://github.com/johang/sd-card-images/blob/master/boards.csv).
