### ISSUE TITLE
Who can tell me what is the default username and password

### ISSUE THREAD

**Issue by ferperji** [johang/sd-card-images#113]
hi,all
I first use the johang SD-CARD-IMAGES for my Tinker Board S and Rock Pi 4C Plus.
I don`t konw default username and password,for example i use linke "https://dl.sd-card-images.johang.se/debians/2024-02-05/ubuntu-noble-armhf-thoo9f.bin.gz",Is the Password thoo9f ? and what is the username ?
Who can tell me ? 
Thanks .

**Comment by ccary64** [comment]
username: root password: thoo9f
