### ISSUE TITLE
Readme update noting zcat on mac osx

### ISSUE THREAD

**Issue by tc0nn** [johang/sd-card-images#126]
You may want to give an example zcat execution on mac OSX... Something like:
zcat < boot-orange_pi_zero2.bin.gz < debian-bookworm-arm64-uom3nu.bin.gz > sd-card.img

**Comment by johang** [comment]
Or you can just do in three steps:

```
$ gunzip boot-orange_pi_zero2.bin.gz
$ gunzip debian-bookworm-arm64-uom3nu.bin.gz
$ cat boot-orange_pi_zero2.bin debian-bookworm-arm64-uom3nu.bin > sd-card.img
```
