### ISSUE TITLE
Banana Pi M2 Berry does not boot

### ISSUE THREAD

**Issue by AlfredoCubitos** [johang/sd-card-images#28]
Hi,

I tried your image for Banana Pi M2 Berry. 
Unfortunately this does not work.
I think this is because the boot partition is empty.
The old images from  banana-pi.org have the kernel and boot config on the boot partition.
Is there a way to boot from the root partition?

**Comment by johang** [comment]
See #19.

**Comment by AlfredoCubitos** [comment]
Thank you! :-)
