### ISSUE TITLE
Resize Partition

### ISSUE THREAD

**Issue by Peskedor** [johang/sd-card-images#33]
Thanks for the images that you provide here - found it really useful!

I'm currently trying to enlarge the / partition, by default it's only ~1.8G for me while I'm using a 32 GB SD card in my banana pi. I tried multiple tutorials to enlarge the file system with fdisk - but it ends up always bricking the system, and it won't boot anymore. Example tutorial: https://erlerobotics.gitbooks.io/erle-robotics-erle-brain-a-linux-brain-for-drones/content/en/tutorials/expandingfilesystem.html

Also tried to install raspi-config which seems to do exactly what is written in the tutorial above, result is the same and the system won't boot anymore.

**Comment by johang** [comment]
This is mentioned on the [tips and tricks](https://sd-card-images.johang.se/tips-and-tricks.html) page.
