### ISSUE TITLE
Orange Pi Zero onboard XR819 WiFi card non existent

### ISSUE THREAD

**Issue by peterbmckinley** [johang/sd-card-images#34]
Hi I'm using current Bookworm for Orange Pi Zero (2023-01-01 / 2023-01-09) but the onboard XR819 WiFi chip is nowhere to be seen. I edited /etc/apt/sources.list to include non-free, ran update, upgrade and dist-upgrade (nothing new installed) and rebooted but I still get this:

```
root@debian:~# iwconfig
lo        no wireless extensions.

end0      no wireless extensions.

root@debian:~# 
```

Any idea if or how I can enable the XR819 WiFi in your build? Note the XR819 chip has a dubious reputation, however in my experience it works well with Armbian (used daily to stream internet radio URL)

**Comment by johang** [comment]
There's no driver for XR819 in mainline kernel or Debian, so it will not work in these images.
