### ISSUE TITLE
Debian 11 command not found for everything.

### ISSUE THREAD

**Issue by Garuizbido** [johang/sd-card-images#40]
I just installed an image on my banana pi m2m, but it has 0 usability. None of the commands work not even sudo and apt install sudo returns with error unable to locate package sudo.

**Comment by johang** [comment]
These are minimal images. They are probably not for beginners.

**Comment by Garuizbido** [comment]
I know these are minimal installs, but I can't get even nano or vim to work. I have gone around this using cat. How can I connect this to the internet in order to download the packages I need?
