### ISSUE TITLE
BananaPi M2+ Wi-Fi not found in default kernel

### ISSUE THREAD

**Issue by rruggiero** [johang/sd-card-images#42]
Firstly, thank you for these images, they are great and your instructions you provide for creating the SD Card is very short and sweet, but more importantly it works !

 I created an image for the BananaPi M2+ (H3 processor) and the image boots fast and loads the ethernet network perfectly, but I cannot find the Wi-Fi interface at all and am having nothing but problems trying to get it up and running; are there instructions on how to load the kernel module to get this device recognised?

Thank you in advance, Rick

**Comment by johang** [comment]
Maybe you need the `firmware-brcm80211` package.
