### ISSUE TITLE
ROC-RK3328-CC Images No Display

### ISSUE THREAD

**Issue by petcat30** [johang/sd-card-images#43]
Hello, I have tried both Bookworm and Bullseye images for the ROC-RK3328-CC and I'm not able to get my display to work. The keyboard lights up and I see the Ethernet port blinking. The monitor is an Acer GN246HL hooked up w/ HDMI.

**Comment by johang** [comment]
These images are very minimal. You shouldn't expect display to work out of the box.

**Comment by petcat30** [comment]
Ah I see, I'm trying an image again. It's been about 15 minutes since I powered on the board and it isn't showing up on my router device list. Any thoughts?

**Comment by johang** [comment]
Hard to say. Can you show the output on the UART console during boot?

**Comment by petcat30** [comment]
I think my issue is I assumed the Firefly roc-rk3328-cc image would work with a Libre Computer Renegade because there isn't a Renegade image. I don't have a UART anyways so gonna close this.
