### ISSUE TITLE
Device support question

### ISSUE THREAD

**Issue by Jackbeef** [johang/sd-card-images#44]
Wanted to know if a ( thehelm email server) HELM  box ( rk3399 EVB board -> rock 4 core ) can be added to devices that are supported by this  community?

Thank you.

**Comment by johang** [comment]
Helm is not supported by mainline Linux and Debian. There are images for rk3399 EVB though.

**Comment by Jackbeef** [comment]
Yes,

Hardware wise this little thing is great for email server. Board also has 2 batteries for power backup.
I also have the Helm V1, looks great for email server as well but it is an earlier rk chip.
https://knowtechie.com/helm-personal-email-service/






-A


On Sat, 11 Mar 2023 14:32:14 -0800, Johan Gunnarsson ***@***.***> wrote:
 
 

Helm is not supported by mainline Linux and Debian. There are images for rk3399 EVB though.

**Comment by Jackbeef** [comment]
Yes, I tried a few but all stop with the trust.img issue.
