### ISSUE TITLE
Images lately won't boot correctly.

### ISSUE THREAD

**Issue by 38github** [johang/sd-card-images#76]
My La Frite (512MB) is not able to correctly boot with the images on your website. The boot goes on to "Starting kernel" or maybe it is "Loading kernel" but nothing happens after that. Your earlier images that I used a couple of months ago did not have this issue.

I have tried several medias but the same thing happens.

**Comment by johang** [comment]
Post logs.

**Comment by 38github** [comment]
Vi kan stänga denna då jag inte har undersökt detta vidare. MvH
