### ISSUE TITLE
Support for IndieDroid Nova SBC?

### ISSUE THREAD

**Issue by Jibun-no-Kage** [johang/sd-card-images#85]
Support for IndieDroid Nova SBC?
[https://ameridroid.com/products/indiedroid-nova](url)

**Comment by johang** [comment]
Yes, would like to support that. Seems to be supported in mainline kernel but not mainline U-Boot.

**Comment by johang** [comment]
I see now that rk3588 has landed in mainline U-Boot.

**Comment by Jibun-no-Kage** [comment]
Excellent!
